/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["browse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{slug}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{slug}/chapters/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["genres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChapterSummary: {
            number: string;
            title?: string | null;
            /** Format: date-time */
            publishedAt: string;
            /** @enum {string} */
            access: "FREE" | "EARLY_ACCESS";
        };
        CursorPageSeriesCard: {
            items: components["schemas"]["SeriesCard"][];
            nextCursor?: string | null;
        };
        Genre: {
            slug: string;
            name: string;
        };
        ImageRef: {
            url: string;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
        };
        SeriesCard: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            /** @enum {string} */
            type: "MANHWA" | "NOVEL";
            /** @enum {string} */
            status: "ONGOING" | "COMPLETED" | "HIATUS";
            /** @enum {string} */
            ageRating: "ALL" | "TEEN" | "MATURE";
            genres: components["schemas"]["Genre"][];
            cover?: components["schemas"]["ImageRef"] | null;
            synopsis: string;
            /** Format: date-time */
            lastPublishedAt?: string | null;
            latestChapters: components["schemas"]["ChapterSummary"][];
        };
        ChapterStats: {
            /** Format: int32 */
            count: number;
            first?: string | null;
            latest?: string | null;
        };
        Edition: {
            language: string;
            original: boolean;
            translatorCredit?: string | null;
        };
        SeriesDetail: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            altTitles: string[];
            synopsis: string;
            /** @enum {string} */
            type: "MANHWA" | "NOVEL";
            /** @enum {string} */
            status: "ONGOING" | "COMPLETED" | "HIATUS";
            /** @enum {string} */
            ageRating: "ALL" | "TEEN" | "MATURE";
            genres: components["schemas"]["Genre"][];
            cover?: components["schemas"]["ImageRef"] | null;
            /** Format: int32 */
            firstReleasedYear?: number | null;
            releaseCadence?: string | null;
            /** Format: date-time */
            lastPublishedAt?: string | null;
            editions: components["schemas"]["Edition"][];
            chapters: components["schemas"]["ChapterStats"];
        };
        CursorPageChapterSummary: {
            items: components["schemas"]["ChapterSummary"][];
            nextCursor?: string | null;
        };
        ChapterContent: {
            series: components["schemas"]["SeriesRef"];
            number: string;
            title?: string | null;
            /** Format: date-time */
            publishedAt: string;
            /** @enum {string} */
            access: "FREE" | "EARLY_ACCESS";
            locked: boolean;
            pages: components["schemas"]["ImageRef"][];
            novel?: components["schemas"]["NovelBody"] | null;
            previous?: string | null;
            next?: string | null;
        };
        NovelBody: {
            markdown: string;
            /** Format: int32 */
            wordCount: number;
        };
        SeriesRef: {
            slug: string;
            title: string;
            /** @enum {string} */
            type: "MANHWA" | "NOVEL";
        };
        HomeResponse: {
            featured: components["schemas"]["SeriesCard"][];
            latestUpdates: components["schemas"]["SeriesCard"][];
            popular: components["schemas"]["Popular"];
        };
        Popular: {
            today: components["schemas"]["RankedSeries"][];
            week: components["schemas"]["RankedSeries"][];
            allTime: components["schemas"]["RankedSeries"][];
        };
        RankedSeries: {
            /** Format: int32 */
            rank: number;
            /** Format: int64 */
            views: number;
            series: components["schemas"]["SeriesCard"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    browse: {
        parameters: {
            query?: {
                q?: string;
                type?: "MANHWA" | "NOVEL";
                status?: "ONGOING" | "COMPLETED" | "HIATUS";
                genres?: string[];
                sort?: "UPDATED" | "NEWEST" | "TITLE";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageSeriesCard"];
                };
            };
        };
    };
    series: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeriesDetail"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                lang?: string;
                order?: "DESC" | "ASC";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageChapterSummary"];
                };
            };
        };
    };
    chapter: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path: {
                slug: string;
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChapterContent"];
                };
            };
        };
    };
    home: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HomeResponse"];
                };
            };
        };
    };
    genres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Genre"][];
                };
            };
        };
    };
}
